### ISSUE TITLE
Can't access the new parts in latest update

### ISSUE THREAD

**Issue by MewtwoFanz** [Valla-Chan/Spore-Mods#1]
I downloaded the latest update, but I don't see the newest parts from the newest update.

**Comment by Valla-Chan** [comment]
@MewtwoFanz which mod are you referring to? if you mean valla vanilla, i have redownloaded this version to check, and all the newest parts are indeed there, just as shown in the image.

**Comment by MewtwoFanz** [comment]
Yes, I mean valla vanilla. I downloaded it, and only the old ones are there

**Comment by Valla-Chan** [comment]
i implore you tro try again, this is all the available parts: 
![image](https://github.com/Valla-Chan/Spore-Mods/assets/20942102/4a13d326-5a75-4327-8d5e-827c72987ab8)
and i have just tested this with the latest version a few minutes ago. the file is downloaded on the page for this mod, and the package file is in mod.zip. simply extract it and install it.
